apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: LoadBalancer
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: django_web
        imagePullPolicy: Never
        name: backend
        ports:
        - containerPort: 8000
        args:
        - ./wait-for-it.sh
        - db:3302
        - --
        - python
        - manage.py
        - runserver
        - 0.0.0.0:8000
        env:
        - name: MYSQL_DATABASE
          value: unicharm
        - name: MYSQL_PASSWORD
          value: unicharm@!?
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: unicharm-dev
        - name: MYSQL_HOST
          value: db
        - name: MYSQL_PORT
          value: "3302"
        resources: {}
      restartPolicy: Always
status: {}
