apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: LoadBalancer
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      volumes:
        - name: volume-code
          hostPath:
            path: /home/vannga/Documents/django_docker
            type: Directory
      containers:
      - args:
        # - ./wait-for-it.sh
        # - database:3306
        # - --
        # - python
        # - manage.py
        # - runserver
        # - 0.0.0.0:8000
        - /bin/bash
        - -c
        - tail -f /dev/null
        image: django_web
        imagePullPolicy: Never
        name: backend
        ports:
        - containerPort: 8000
        volumeMounts:
          - mountPath: /code/
            name: volume-code
        resources: {}
      restartPolicy: Always
status: {}
